steps:
- script : npm install
- script : npm install -g gulp-cli
- script : pip install requests
- script : mkdir -p reports
- script : mkdir -p output
- script : chmod +x ./scripts/upload_reports_to_confluence.py
- script : gulp cucumber:android:local
- script : wait
- script : gulp generate:report --osVersion 8 --platformName Android
- script : gulp automation:run:result
- script : ./scripts/upload_reports_to_confluence.py; fi